# spring config
spring:
  profiles:
    active: @profileActive@
  application:
    name: uni-boot-admin
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

# mybatis plus 配置
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: top.cadecode.**.bean
  type-enums-package: top.cadecode.**.enums
  configuration:
    map-underscore-to-camel-case: true

# log config
logging:
  file:
    path: /log/${uni-boot.config.name}

